version: 2
jobs:
  test-alpine:
    docker:
      - image: alpine:latest
    steps:
      - run: |
          apk add --no-cache bats curl ca-certificates git wget bash xz coreutils make tzdata
          GOMPLATE_VERSION=v2.2.0
          wget https://github.com/hairyhenderson/gomplate/releases/download/${GOMPLATE_VERSION}/gomplate_linux-amd64-slim
          chmod +x gomplate_linux-amd64-slim
          mv gomplate_linux-amd64-slim /usr/local/bin/gomplate
          gomplate --version

      - checkout
      - run: make
      - run: ./test.sh
  test-debian:
    docker:
      - image: buildpack-deps:stretch
    steps:
      - run: |
          apt-get update
          apt-get install -y bats shellcheck
          GOMPLATE_VERSION=v2.2.0
          wget https://github.com/hairyhenderson/gomplate/releases/download/${GOMPLATE_VERSION}/gomplate_linux-amd64-slim
          chmod +x gomplate_linux-amd64-slim
          mv gomplate_linux-amd64-slim /usr/local/bin/gomplate
          gomplate --version

      - checkout
      - run: make
      - run: ./test.sh
      - run: shellcheck rendered/panubo-functions.sh
workflows:
  version: 2
  test:
    jobs:
      - test-debian
      - test-alpine
