name: CI Tests

on:
  push:
    branches:
      - '*'
    tags:
      - '!v*'  # don't trigger on release tags

jobs:
  test_debian:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Build Debian Linux
        run: make build-docker-debian

      - name: Test Debian Linux
        run: make test-docker-debian

  test_alpine:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Build Alpine Linux
        run: make build-docker-alpine

      - name: Test Alpine Linux
        run: make test-docker-alpine
